// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.xiahou.yu.paasmetacore.protobuf;

public final class EnumMessageProto {
  private EnumMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code SexEnum}
   */
  public enum SexEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT_SEX = 0;</code>
     */
    DEFAULT_SEX(0),
    /**
     * <code>MALE = 1;</code>
     */
    MALE(1),
    /**
     * <code>FEMALE = 2;</code>
     */
    FEMALE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT_SEX = 0;</code>
     */
    public static final int DEFAULT_SEX_VALUE = 0;
    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <code>FEMALE = 2;</code>
     */
    public static final int FEMALE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SexEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SexEnum forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT_SEX;
        case 1: return MALE;
        case 2: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SexEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SexEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SexEnum>() {
            public SexEnum findValueByNumber(int number) {
              return SexEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final SexEnum[] VALUES = values();

    public static SexEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SexEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SexEnum)
  }

  /**
   * Protobuf enum {@code SubjectEnum}
   */
  public enum SubjectEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT_SUBJECT = 0;</code>
     */
    DEFAULT_SUBJECT(0),
    /**
     * <code>CHINESE = 1;</code>
     */
    CHINESE(1),
    /**
     * <code>MATH = 2;</code>
     */
    MATH(2),
    /**
     * <code>ENGLISH = 3;</code>
     */
    ENGLISH(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT_SUBJECT = 0;</code>
     */
    public static final int DEFAULT_SUBJECT_VALUE = 0;
    /**
     * <code>CHINESE = 1;</code>
     */
    public static final int CHINESE_VALUE = 1;
    /**
     * <code>MATH = 2;</code>
     */
    public static final int MATH_VALUE = 2;
    /**
     * <code>ENGLISH = 3;</code>
     */
    public static final int ENGLISH_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SubjectEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SubjectEnum forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT_SUBJECT;
        case 1: return CHINESE;
        case 2: return MATH;
        case 3: return ENGLISH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SubjectEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SubjectEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SubjectEnum>() {
            public SubjectEnum findValueByNumber(int number) {
              return SubjectEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final SubjectEnum[] VALUES = values();

    public static SubjectEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SubjectEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SubjectEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto*0\n\007SexEnum\022\017\n\013DEFAULT_SEX\020" +
      "\000\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002*F\n\013SubjectEnum\022\023" +
      "\n\017DEFAULT_SUBJECT\020\000\022\013\n\007CHINESE\020\001\022\010\n\004MATH" +
      "\020\002\022\013\n\007ENGLISH\020\003B7\n#com.xiahou.yu.paasmet" +
      "acore.protobufB\020EnumMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
