// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foo_service.proto

package com.xiahou.yu.paasmetacore.protobuf;

public final class FooServiceFoo {
  private FooServiceFoo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021foo_service.proto\032\016foo_demo.proto\032\nuse" +
      "r.proto2)\n\nFooService\022\033\n\014GetSomething\022\005." +
      "User\032\004.FooB4\n#com.xiahou.yu.paasmetacore" +
      ".protobufB\rFooServiceFoob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xiahou.yu.paasmetacore.protobuf.FooDemo.getDescriptor(),
          com.xiahou.yu.paasmetacore.protobuf.MessageProto.getDescriptor(),
        });
    com.xiahou.yu.paasmetacore.protobuf.FooDemo.getDescriptor();
    com.xiahou.yu.paasmetacore.protobuf.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
