// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xiahou.yu.paasmetacore.protobuf;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.SexEnum sex = 3;</code>
     * @return The enum numeric value on the wire for sex.
     */
    int getSexValue();
    /**
     * <code>.SexEnum sex = 3;</code>
     * @return The sex.
     */
    com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum getSex();

    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    int getGradeCount();
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    boolean containsGrade(
        int key);
    /**
     * Use {@link #getGradeMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
    getGrade();
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
    getGradeMap();
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    /* nullable */
com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getGradeOrDefault(
        int key,
        /* nullable */
com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo defaultValue);
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getGradeOrThrow(
        int key);

    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    java.util.List<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser> 
        getParentList();
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser getParent(int index);
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    int getParentCount();
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    java.util.List<? extends com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder> 
        getParentOrBuilderList();
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder getParentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      sex_ = 0;
      parent_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetGrade();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.class, com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.Builder.class);
    }

    public static final int AGE_FIELD_NUMBER = 1;
    private int age_ = 0;
    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_ = 0;
    /**
     * <code>.SexEnum sex = 3;</code>
     * @return The enum numeric value on the wire for sex.
     */
    @java.lang.Override public int getSexValue() {
      return sex_;
    }
    /**
     * <code>.SexEnum sex = 3;</code>
     * @return The sex.
     */
    @java.lang.Override public com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum getSex() {
      com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum result = com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum.forNumber(sex_);
      return result == null ? com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum.UNRECOGNIZED : result;
    }

    public static final int GRADE_FIELD_NUMBER = 4;
    private static final class GradeDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>newDefaultInstance(
                  com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_User_GradeEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> grade_;
    private com.google.protobuf.MapField<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
    internalGetGrade() {
      if (grade_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            GradeDefaultEntryHolder.defaultEntry);
      }
      return grade_;
    }
    public int getGradeCount() {
      return internalGetGrade().getMap().size();
    }
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    @java.lang.Override
    public boolean containsGrade(
        int key) {
      
      return internalGetGrade().getMap().containsKey(key);
    }
    /**
     * Use {@link #getGradeMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> getGrade() {
      return getGradeMap();
    }
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> getGradeMap() {
      return internalGetGrade().getMap();
    }
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getGradeOrDefault(
        int key,
        /* nullable */
com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo defaultValue) {
      
      java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> map =
          internalGetGrade().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
     */
    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getGradeOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> map =
          internalGetGrade().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PARENT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser> parent_;
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser> getParentList() {
      return parent_;
    }
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder> 
        getParentOrBuilderList() {
      return parent_;
    }
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    @java.lang.Override
    public int getParentCount() {
      return parent_.size();
    }
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser getParent(int index) {
      return parent_.get(index);
    }
    /**
     * <code>repeated .ParentUser parent = 5;</code>
     */
    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder getParentOrBuilder(
        int index) {
      return parent_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (sex_ != com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum.DEFAULT_SEX.getNumber()) {
        output.writeEnum(3, sex_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetGrade(),
          GradeDefaultEntryHolder.defaultEntry,
          4);
      for (int i = 0; i < parent_.size(); i++) {
        output.writeMessage(5, parent_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (sex_ != com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum.DEFAULT_SEX.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, sex_);
      }
      for (java.util.Map.Entry<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> entry
           : internalGetGrade().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
        grade__ = GradeDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, grade__);
      }
      for (int i = 0; i < parent_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, parent_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MessageProto.User)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MessageProto.User other = (com.xiahou.yu.paasmetacore.protobuf.MessageProto.User) obj;

      if (getAge()
          != other.getAge()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (sex_ != other.sex_) return false;
      if (!internalGetGrade().equals(
          other.internalGetGrade())) return false;
      if (!getParentList()
          .equals(other.getParentList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      if (!internalGetGrade().getMap().isEmpty()) {
        hash = (37 * hash) + GRADE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetGrade().hashCode();
      }
      if (getParentCount() > 0) {
        hash = (37 * hash) + PARENT_FIELD_NUMBER;
        hash = (53 * hash) + getParentList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MessageProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_User_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetGrade();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableGrade();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.class, com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        age_ = 0;
        name_ = "";
        sex_ = 0;
        internalGetMutableGrade().clear();
        if (parentBuilder_ == null) {
          parent_ = java.util.Collections.emptyList();
        } else {
          parent_ = null;
          parentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.User getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.User build() {
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.User buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.User result = new com.xiahou.yu.paasmetacore.protobuf.MessageProto.User(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.xiahou.yu.paasmetacore.protobuf.MessageProto.User result) {
        if (parentBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            parent_ = java.util.Collections.unmodifiableList(parent_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.parent_ = parent_;
        } else {
          result.parent_ = parentBuilder_.build();
        }
      }

      private void buildPartial0(com.xiahou.yu.paasmetacore.protobuf.MessageProto.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sex_ = sex_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.grade_ = internalGetGrade();
          result.grade_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MessageProto.User) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MessageProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MessageProto.User other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MessageProto.User.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        internalGetMutableGrade().mergeFrom(
            other.internalGetGrade());
        bitField0_ |= 0x00000008;
        if (parentBuilder_ == null) {
          if (!other.parent_.isEmpty()) {
            if (parent_.isEmpty()) {
              parent_ = other.parent_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureParentIsMutable();
              parent_.addAll(other.parent_);
            }
            onChanged();
          }
        } else {
          if (!other.parent_.isEmpty()) {
            if (parentBuilder_.isEmpty()) {
              parentBuilder_.dispose();
              parentBuilder_ = null;
              parent_ = other.parent_;
              bitField0_ = (bitField0_ & ~0x00000010);
              parentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParentFieldBuilder() : null;
            } else {
              parentBuilder_.addAllMessages(other.parent_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                sex_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
                grade__ = input.readMessage(
                    GradeDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableGrade().getMutableMap().put(
                    grade__.getKey(), grade__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser m =
                    input.readMessage(
                        com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.parser(),
                        extensionRegistry);
                if (parentBuilder_ == null) {
                  ensureParentIsMutable();
                  parent_.add(m);
                } else {
                  parentBuilder_.addMessage(m);
                }
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <code>int32 age = 1;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 1;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>.SexEnum sex = 3;</code>
       * @return The enum numeric value on the wire for sex.
       */
      @java.lang.Override public int getSexValue() {
        return sex_;
      }
      /**
       * <code>.SexEnum sex = 3;</code>
       * @param value The enum numeric value on the wire for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.SexEnum sex = 3;</code>
       * @return The sex.
       */
      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum getSex() {
        com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum result = com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum.forNumber(sex_);
        return result == null ? com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.SexEnum sex = 3;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.SexEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.SexEnum sex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> grade_;
      private com.google.protobuf.MapField<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
          internalGetGrade() {
        if (grade_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              GradeDefaultEntryHolder.defaultEntry);
        }
        return grade_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
          internalGetMutableGrade() {
        if (grade_ == null) {
          grade_ = com.google.protobuf.MapField.newMapField(
              GradeDefaultEntryHolder.defaultEntry);
        }
        if (!grade_.isMutable()) {
          grade_ = grade_.copy();
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return grade_;
      }
      public int getGradeCount() {
        return internalGetGrade().getMap().size();
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      @java.lang.Override
      public boolean containsGrade(
          int key) {
        
        return internalGetGrade().getMap().containsKey(key);
      }
      /**
       * Use {@link #getGradeMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> getGrade() {
        return getGradeMap();
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> getGradeMap() {
        return internalGetGrade().getMap();
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getGradeOrDefault(
          int key,
          /* nullable */
com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo defaultValue) {
        
        java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> map =
            internalGetGrade().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getGradeOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> map =
            internalGetGrade().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearGrade() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableGrade().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      public Builder removeGrade(
          int key) {
        
        internalGetMutableGrade().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo>
          getMutableGrade() {
        bitField0_ |= 0x00000008;
        return internalGetMutableGrade().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      public Builder putGrade(
          int key,
          com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo value) {
        
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableGrade().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;int32, .GradeInfo&gt; grade = 4;</code>
       */
      public Builder putAllGrade(
          java.util.Map<java.lang.Integer, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo> values) {
        internalGetMutableGrade().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }

      private java.util.List<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser> parent_ =
        java.util.Collections.emptyList();
      private void ensureParentIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          parent_ = new java.util.ArrayList<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser>(parent_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder> parentBuilder_;

      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public java.util.List<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser> getParentList() {
        if (parentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parent_);
        } else {
          return parentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public int getParentCount() {
        if (parentBuilder_ == null) {
          return parent_.size();
        } else {
          return parentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser getParent(int index) {
        if (parentBuilder_ == null) {
          return parent_.get(index);
        } else {
          return parentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder setParent(
          int index, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser value) {
        if (parentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParentIsMutable();
          parent_.set(index, value);
          onChanged();
        } else {
          parentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder setParent(
          int index, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder builderForValue) {
        if (parentBuilder_ == null) {
          ensureParentIsMutable();
          parent_.set(index, builderForValue.build());
          onChanged();
        } else {
          parentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder addParent(com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser value) {
        if (parentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParentIsMutable();
          parent_.add(value);
          onChanged();
        } else {
          parentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder addParent(
          int index, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser value) {
        if (parentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParentIsMutable();
          parent_.add(index, value);
          onChanged();
        } else {
          parentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder addParent(
          com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder builderForValue) {
        if (parentBuilder_ == null) {
          ensureParentIsMutable();
          parent_.add(builderForValue.build());
          onChanged();
        } else {
          parentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder addParent(
          int index, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder builderForValue) {
        if (parentBuilder_ == null) {
          ensureParentIsMutable();
          parent_.add(index, builderForValue.build());
          onChanged();
        } else {
          parentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder addAllParent(
          java.lang.Iterable<? extends com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser> values) {
        if (parentBuilder_ == null) {
          ensureParentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, parent_);
          onChanged();
        } else {
          parentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder clearParent() {
        if (parentBuilder_ == null) {
          parent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          parentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public Builder removeParent(int index) {
        if (parentBuilder_ == null) {
          ensureParentIsMutable();
          parent_.remove(index);
          onChanged();
        } else {
          parentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder getParentBuilder(
          int index) {
        return getParentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder getParentOrBuilder(
          int index) {
        if (parentBuilder_ == null) {
          return parent_.get(index);  } else {
          return parentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public java.util.List<? extends com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder> 
           getParentOrBuilderList() {
        if (parentBuilder_ != null) {
          return parentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parent_);
        }
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder addParentBuilder() {
        return getParentFieldBuilder().addBuilder(
            com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.getDefaultInstance());
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder addParentBuilder(
          int index) {
        return getParentFieldBuilder().addBuilder(
            index, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.getDefaultInstance());
      }
      /**
       * <code>repeated .ParentUser parent = 5;</code>
       */
      public java.util.List<com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder> 
           getParentBuilderList() {
        return getParentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder> 
          getParentFieldBuilder() {
        if (parentBuilder_ == null) {
          parentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder>(
                  parent_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          parent_ = null;
        }
        return parentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.xiahou.yu.paasmetacore.protobuf.MessageProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MessageProto.User();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MessageProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GradeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GradeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double score = 1;</code>
     * @return The score.
     */
    double getScore();

    /**
     * <code>int32 rank = 2;</code>
     * @return The rank.
     */
    int getRank();
  }
  /**
   * Protobuf type {@code GradeInfo}
   */
  public static final class GradeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GradeInfo)
      GradeInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GradeInfo.newBuilder() to construct.
    private GradeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GradeInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GradeInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_GradeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_GradeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.class, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private double score_ = 0D;
    /**
     * <code>double score = 1;</code>
     * @return The score.
     */
    @java.lang.Override
    public double getScore() {
      return score_;
    }

    public static final int RANK_FIELD_NUMBER = 2;
    private int rank_ = 0;
    /**
     * <code>int32 rank = 2;</code>
     * @return The rank.
     */
    @java.lang.Override
    public int getRank() {
      return rank_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(score_) != 0) {
        output.writeDouble(1, score_);
      }
      if (rank_ != 0) {
        output.writeInt32(2, rank_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(score_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, score_);
      }
      if (rank_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rank_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo other = (com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo) obj;

      if (java.lang.Double.doubleToLongBits(getScore())
          != java.lang.Double.doubleToLongBits(
              other.getScore())) return false;
      if (getRank()
          != other.getRank()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getScore()));
      hash = (37 * hash) + RANK_FIELD_NUMBER;
      hash = (53 * hash) + getRank();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GradeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GradeInfo)
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_GradeInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_GradeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.class, com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        score_ = 0D;
        rank_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_GradeInfo_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo build() {
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo result = new com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.score_ = score_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rank_ = rank_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo.getDefaultInstance()) return this;
        if (other.getScore() != 0D) {
          setScore(other.getScore());
        }
        if (other.getRank() != 0) {
          setRank(other.getRank());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                score_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 16: {
                rank_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double score_ ;
      /**
       * <code>double score = 1;</code>
       * @return The score.
       */
      @java.lang.Override
      public double getScore() {
        return score_;
      }
      /**
       * <code>double score = 1;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(double value) {
        
        score_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double score = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0D;
        onChanged();
        return this;
      }

      private int rank_ ;
      /**
       * <code>int32 rank = 2;</code>
       * @return The rank.
       */
      @java.lang.Override
      public int getRank() {
        return rank_;
      }
      /**
       * <code>int32 rank = 2;</code>
       * @param value The rank to set.
       * @return This builder for chaining.
       */
      public Builder setRank(int value) {
        
        rank_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rank = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rank_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GradeInfo)
    }

    // @@protoc_insertion_point(class_scope:GradeInfo)
    private static final com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GradeInfo>
        PARSER = new com.google.protobuf.AbstractParser<GradeInfo>() {
      @java.lang.Override
      public GradeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GradeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GradeInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MessageProto.GradeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParentUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ParentUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string relation = 1;</code>
     * @return The relation.
     */
    java.lang.String getRelation();
    /**
     * <code>string relation = 1;</code>
     * @return The bytes for relation.
     */
    com.google.protobuf.ByteString
        getRelationBytes();

    /**
     * <code>string tel = 2;</code>
     * @return The tel.
     */
    java.lang.String getTel();
    /**
     * <code>string tel = 2;</code>
     * @return The bytes for tel.
     */
    com.google.protobuf.ByteString
        getTelBytes();
  }
  /**
   * Protobuf type {@code ParentUser}
   */
  public static final class ParentUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ParentUser)
      ParentUserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParentUser.newBuilder() to construct.
    private ParentUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParentUser() {
      relation_ = "";
      tel_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ParentUser();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_ParentUser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_ParentUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.class, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder.class);
    }

    public static final int RELATION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object relation_ = "";
    /**
     * <code>string relation = 1;</code>
     * @return The relation.
     */
    @java.lang.Override
    public java.lang.String getRelation() {
      java.lang.Object ref = relation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relation_ = s;
        return s;
      }
    }
    /**
     * <code>string relation = 1;</code>
     * @return The bytes for relation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRelationBytes() {
      java.lang.Object ref = relation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tel_ = "";
    /**
     * <code>string tel = 2;</code>
     * @return The tel.
     */
    @java.lang.Override
    public java.lang.String getTel() {
      java.lang.Object ref = tel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tel_ = s;
        return s;
      }
    }
    /**
     * <code>string tel = 2;</code>
     * @return The bytes for tel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTelBytes() {
      java.lang.Object ref = tel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, relation_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tel_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, relation_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser other = (com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser) obj;

      if (!getRelation()
          .equals(other.getRelation())) return false;
      if (!getTel()
          .equals(other.getTel())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RELATION_FIELD_NUMBER;
      hash = (53 * hash) + getRelation().hashCode();
      hash = (37 * hash) + TEL_FIELD_NUMBER;
      hash = (53 * hash) + getTel().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ParentUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ParentUser)
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_ParentUser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_ParentUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.class, com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        relation_ = "";
        tel_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.internal_static_ParentUser_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser build() {
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser result = new com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.relation_ = relation_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tel_ = tel_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser.getDefaultInstance()) return this;
        if (!other.getRelation().isEmpty()) {
          relation_ = other.relation_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTel().isEmpty()) {
          tel_ = other.tel_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                relation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tel_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object relation_ = "";
      /**
       * <code>string relation = 1;</code>
       * @return The relation.
       */
      public java.lang.String getRelation() {
        java.lang.Object ref = relation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          relation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string relation = 1;</code>
       * @return The bytes for relation.
       */
      public com.google.protobuf.ByteString
          getRelationBytes() {
        java.lang.Object ref = relation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string relation = 1;</code>
       * @param value The relation to set.
       * @return This builder for chaining.
       */
      public Builder setRelation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        relation_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string relation = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelation() {
        relation_ = getDefaultInstance().getRelation();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string relation = 1;</code>
       * @param value The bytes for relation to set.
       * @return This builder for chaining.
       */
      public Builder setRelationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        relation_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tel_ = "";
      /**
       * <code>string tel = 2;</code>
       * @return The tel.
       */
      public java.lang.String getTel() {
        java.lang.Object ref = tel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tel = 2;</code>
       * @return The bytes for tel.
       */
      public com.google.protobuf.ByteString
          getTelBytes() {
        java.lang.Object ref = tel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tel = 2;</code>
       * @param value The tel to set.
       * @return This builder for chaining.
       */
      public Builder setTel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string tel = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTel() {
        tel_ = getDefaultInstance().getTel();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string tel = 2;</code>
       * @param value The bytes for tel to set.
       * @return This builder for chaining.
       */
      public Builder setTelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ParentUser)
    }

    // @@protoc_insertion_point(class_scope:ParentUser)
    private static final com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParentUser>
        PARSER = new com.google.protobuf.AbstractParser<ParentUser>() {
      @java.lang.Override
      public ParentUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ParentUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParentUser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MessageProto.ParentUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_GradeEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_GradeEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GradeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GradeInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParentUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParentUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\013enums.proto\"\260\001\n\004User\022\013\n\003ag" +
      "e\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\025\n\003sex\030\003 \001(\0162\010.Sex" +
      "Enum\022\037\n\005grade\030\004 \003(\0132\020.User.GradeEntry\022\033\n" +
      "\006parent\030\005 \003(\0132\013.ParentUser\0328\n\nGradeEntry" +
      "\022\013\n\003key\030\001 \001(\005\022\031\n\005value\030\002 \001(\0132\n.GradeInfo" +
      ":\0028\001\"(\n\tGradeInfo\022\r\n\005score\030\001 \001(\001\022\014\n\004rank" +
      "\030\002 \001(\005\"+\n\nParentUser\022\020\n\010relation\030\001 \001(\t\022\013" +
      "\n\003tel\030\002 \001(\tB3\n#com.xiahou.yu.paasmetacor" +
      "e.protobufB\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.getDescriptor(),
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Age", "Name", "Sex", "Grade", "Parent", });
    internal_static_User_GradeEntry_descriptor =
      internal_static_User_descriptor.getNestedTypes().get(0);
    internal_static_User_GradeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_GradeEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GradeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GradeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GradeInfo_descriptor,
        new java.lang.String[] { "Score", "Rank", });
    internal_static_ParentUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ParentUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParentUser_descriptor,
        new java.lang.String[] { "Relation", "Tel", });
    com.xiahou.yu.paasmetacore.protobuf.EnumMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
