// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta_domain_model.proto

package com.xiahou.yu.paasmetacore.protobuf;

public final class MetaDomainModelProto {
  private MetaDomainModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DomainModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DomainModel)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *  message Context {
   *AbstractModel abstractModel = 1;
   *}
   *message Property {
   *AbstractProperty abstractProperty = 2;
   *}
   *repeated Context contexts = 1;
   *repeated Property props = 2;
   * </pre>
   *
   * Protobuf type {@code DomainModel}
   */
  public static final class DomainModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DomainModel)
      DomainModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DomainModel.newBuilder() to construct.
    private DomainModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DomainModel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DomainModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DomainModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DomainModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel other = (com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *  message Context {
     *AbstractModel abstractModel = 1;
     *}
     *message Property {
     *AbstractProperty abstractProperty = 2;
     *}
     *repeated Context contexts = 1;
     *repeated Property props = 2;
     * </pre>
     *
     * Protobuf type {@code DomainModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DomainModel)
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DomainModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DomainModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DomainModel_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel build() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel result = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DomainModel)
    }

    // @@protoc_insertion_point(class_scope:DomainModel)
    private static final com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DomainModel>
        PARSER = new com.google.protobuf.AbstractParser<DomainModel>() {
      @java.lang.Override
      public DomainModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DomainModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DomainModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DomainModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UIModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UIModel)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code UIModel}
   */
  public static final class UIModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UIModel)
      UIModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UIModel.newBuilder() to construct.
    private UIModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UIModel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UIModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_UIModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_UIModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel other = (com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UIModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UIModel)
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_UIModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_UIModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_UIModel_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel build() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel result = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UIModel)
    }

    // @@protoc_insertion_point(class_scope:UIModel)
    private static final com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UIModel>
        PARSER = new com.google.protobuf.AbstractParser<UIModel>() {
      @java.lang.Override
      public UIModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UIModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UIModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.UIModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EntityModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityModel)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code EntityModel}
   */
  public static final class EntityModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityModel)
      EntityModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityModel.newBuilder() to construct.
    private EntityModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityModel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EntityModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_EntityModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_EntityModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel other = (com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EntityModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityModel)
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_EntityModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_EntityModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_EntityModel_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel build() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel result = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityModel)
    }

    // @@protoc_insertion_point(class_scope:EntityModel)
    private static final com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityModel>
        PARSER = new com.google.protobuf.AbstractParser<EntityModel>() {
      @java.lang.Override
      public EntityModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EntityModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.EntityModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataModel)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code DataModel}
   */
  public static final class DataModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataModel)
      DataModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataModel.newBuilder() to construct.
    private DataModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataModel() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DataModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DataModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel)) {
        return super.equals(obj);
      }
      com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel other = (com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataModel)
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DataModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DataModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.class, com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.Builder.class);
      }

      // Construct using com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.internal_static_DataModel_descriptor;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel getDefaultInstanceForType() {
        return com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel build() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel buildPartial() {
        com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel result = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel) {
          return mergeFrom((com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel other) {
        if (other == com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataModel)
    }

    // @@protoc_insertion_point(class_scope:DataModel)
    private static final com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel();
    }

    public static com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataModel>
        PARSER = new com.google.protobuf.AbstractParser<DataModel>() {
      @java.lang.Override
      public DataModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiahou.yu.paasmetacore.protobuf.MetaDomainModelProto.DataModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DomainModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DomainModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UIModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UIModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027meta_domain_model.proto\"\r\n\013DomainModel" +
      "\"\t\n\007UIModel\"\r\n\013EntityModel\"\013\n\tDataModelB" +
      ";\n#com.xiahou.yu.paasmetacore.protobufB\024" +
      "MetaDomainModelProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DomainModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DomainModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DomainModel_descriptor,
        new java.lang.String[] { });
    internal_static_UIModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UIModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UIModel_descriptor,
        new java.lang.String[] { });
    internal_static_EntityModel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EntityModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityModel_descriptor,
        new java.lang.String[] { });
    internal_static_DataModel_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DataModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataModel_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
