spring:
  application:
    name: paas-data-core-design

  # 允许Bean定义覆盖
  main:
    allow-bean-definition-overriding: true

  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5432/db_xiaho?currentSchema=s_xiaho
    username: postgres
    password: Wanghaoxin115277
    driver-class-name: org.postgresql.Driver

    # 连接池配置
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: HikariCP-DataCore

  # Spring Data JDBC 配置
  data:
    jdbc:
      repositories:
        enabled: true

  # SQL 日志配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 日志配置
logging:
  level:
    com.xiahou.yu.paasdatacore.design: DEBUG
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
